#!/bin/sh
# To setup git hooks run:
#   > git config core.hooksPath .git-hooks || echo 'Not in a git repo'

echo "Running .git-hooks/pre-commit..."

npx madge --circular --extensions ts ./libs
npx madge --circular --extensions ts ./apps

pnpx lint-staged
