# Setup steps for the GitHub Copilot coding agent.
# This file configures the environment before Copilot starts working on tasks.
# See: https://docs.github.com/copilot/how-tos/agents/copilot-coding-agent/customizing-copilot-coding-agent

name: "Copilot Setup Steps"

on: workflow_dispatch

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          cache: 'pnpm'
          node-version: '24'

      - name: Install dependencies
        run: pnpm install
