import { addIcons } from 'ionicons';

import {
  add,
  personAdd,
  listOutline,
  checkmarkOutline,
  peopleOutline,
  logOutOutline,
  fileTrayStackedOutline,
  cashOutline,
  carOutline,
  carSportOutline,
  calendarOutline,
  createOutline,
  checkmarkCircleOutline,
  radioButtonOffOutline,
  addOutline,
  addCircleOutline,
  homeOutline,
  duplicateOutline,
  personOutline,
  documentsOutline,
  peopleCircleOutline,
  barChartOutline,
  chevronForwardSharp,
  chevronForwardOutline,
  chevronDownOutline,
  chevronBackSharp,
  todayOutline,
  closeOutline,
  searchOutline,
  personAddOutline,
  call,
  arrowDown,
  arrowDownOutline,
  trash,
} from 'ionicons/icons';

export function registerIonicons() {
  // TODO: try to add icons at components level?
  addIcons({
    add,
    personAdd,
    listOutline,
    checkmarkOutline,
    peopleOutline,
    logOutOutline,
    fileTrayStackedOutline,
    cashOutline,
    carOutline,
    carSportOutline,
    calendarOutline,
    createOutline,
    radioButtonOffOutline,
    addOutline,
    addCircleOutline,
    homeOutline,
    checkmarkCircleOutline,
    duplicateOutline,
    personOutline,
    documentsOutline,
    peopleCircleOutline,
    barChartOutline,
    chevronForwardSharp,
    chevronForwardOutline,
    chevronDownOutline,
    chevronBackSharp,
    todayOutline,
    closeOutline,
    searchOutline,
    personAddOutline,
    call,
    arrowDown,
    arrowDownOutline,
    trash,
  });
}
