name: 'Checkout & PNPM install'

description: "Checkouts repo (depth=0), installs PNPM, runs `pnpm install`"

runs:
    using: "composite"
    steps:
        -   name: Checkout repository
            uses: actions/checkout@v4
            with:
                fetch-depth: 0

        -   run: git rev-parse HEAD
        -   run: git rev-parse HEAD~1

        -   name: Setup NodeJS
            uses: actions/setup-node@v4
            with:
                node-version: '16'

        -   name: Install PNPM
            uses: pnpm/action-setup@v2
            with:
                version: 8
                run_install: false

        -   run: pnpm --version

        -   name: Get pnpm store directory
            id: pnpm-cache
            run: |
                echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

        -   name: Cache PNPM store directory
            uses: actions/cache@v3
            with:
                path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
                key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                restore-keys: |
                    ${{ runner.os }}-pnpm-store-

        -   run: pnpm install
