export * from './age-group/age-group-form.component';
export * from './emails-form/emails-form.component';
export * from './gender-form/gender-form.component';
export * from './names-form/names-form.component';
export * from './person-form-wizard.component';
export * from './person-form.module';
export * from './phones-form/phones-form.component';
export * from './relationship-form/relationship-form.component';
export * from './roles-form/roles-form.component';
