module.exports = {
  projects: [
    '<rootDir>/apps/emptyapp',
    '<rootDir>/libs/core',
    '<rootDir>/libs/logging',
    '<rootDir>/libs/analytics',
    '<rootDir>/libs/auth',
    '<rootDir>/libs/auth-ui',
    '<rootDir>/libs/random',
    '<rootDir>/libs/app',
    '<rootDir>/libs/auth-models',
    '<rootDir>/libs/data',
    '<rootDir>/libs/api',
    '<rootDir>/libs/datatug/pages/home',
    '<rootDir>/libs/animations',
    '<rootDir>/libs/components/error-card',
    '<rootDir>/libs/components/card-list',
    '<rootDir>/libs/datatug/models',
    '<rootDir>/libs/datetime',
    '<rootDir>/libs/datatug/pages/signed-out',
    '<rootDir>/libs/datatug/core',
    '<rootDir>/libs/datatug/pages/my',
    '<rootDir>/libs/auth-login-page',
  ],
};
