#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

local_branch="$(git rev-parse --abbrev-ref HEAD)"
valid_prefixes="renovate|feature|bugfix|improvement"
valid_branch_regex="^main|($valid_prefixes)\/[a-zA-Z0-9._-]+$"

# shellcheck disable=SC2039
if [[ ! $local_branch =~ $valid_branch_regex ]]
then
    RED='\033[0;31m'
    NO_COLOR='\033[0m'
    BIYellow='\033[1;93m'
    echo -e "${RED}Branch names in this project must be 'main' of have 1 of the following prefixes (followed by / and a suffix):${NO_COLOR} $valid_prefixes.\nYour local branch name is '${RED}$local_branch${NO_COLOR}'. ${BIYellow}You should rename your branch to a valid name and try again.${NO_COLOR}"
    exit 1
fi

pnpx lint-staged
